name: Build & deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'develop'
    - run: flutter --version
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Test project
      run: flutter test
    
    - name: Build release project
      run: flutter build web

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build/web
  
  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build